### ISSUE TITLE
Any request lose TOR connection.

### ISSUE THREAD

**Issue by DMantis** [3xplcom/Core#17]
Steps to reproduce:
- open the onion resource version with the link from the footer or meta header (suggested by TOR).
- click anything on the page (like home page banner),  search for address, etc
- request is sent to clearnet domain instead of onion backend.

**Comment by Har01d** [comment]
Thanks for noticing! It seems like we had too tight caching rules. This is now resolved.
BTW, we've moved to a cool new .onion address: http://3xplor3rzajysy4j5fi3g3k27vivfcw75zjxdb2tg2wpz3i4cdiyhxyd.onion/

**Comment by DMantis** [comment]
Original issue seems to be fixed. 

Though TOR is now suggesting to go to old link because of outdated `onion-location` header.

Impressive response times for onion resource, btw. :+1:

**Comment by Har01d** [comment]
> Though TOR is now suggesting to go to old link because of outdated `onion-location` header.

The clearnet website has also been updated now!

> Impressive response times for onion resource, btw.

Thanks! But I guess that's until some constant DoS attacks begin ¯\_(ツ)_/¯
It always happens on Tor...
But generally one of our goals is to keep the explorers as lightweight as possible. They also work without JS.
