### ISSUE TITLE
Fix onion version redirect to clearnert

### ISSUE THREAD

**Issue by BenMalinski** [3xplcom/Core#33]
Could you please fix the onion version of 3xpl explorer?

When I use onion version http://3xplor3rzajysy4j5fi3g3k27vivfcw75zjxdb2tg2wpz3i4cdiyhxyd.onion/
and search for address, e.g. bc1qxy2kgdygjrsqtzq2n0yrf2493p83kkfjhx0wlh
it redirects to the clearnet version of the website
https://3xpl.com/bitcoin/address/bc1qxy2kgdygjrsqtzq2n0yrf2493p83kkfjhx0wlh

I'd expect it to stay on onion version.

**Comment by Har01d** [comment]
This has been fixed, thanks once again!
![image](https://github.com/3xplcom/Core/assets/14060856/413cce73-4b0e-4583-8ee3-9e8ff8b79131)
